import { z } from 'zod';
import { optStr, optFloat, optInt, updStr, updFloat, updInt } from './common';

export const productCreateSchema = z.object({
    name: z.string().trim().min(1, 'Tên sản phẩm bắt buộc'),
    category: z.string().trim().min(1, 'Danh mục bắt buộc'),
    unit: z.string().trim().min(1, 'Đơn vị bắt buộc'),
    importPrice: optFloat,
    salePrice: optFloat,
    stock: optInt,
    minStock: optInt,
    supplier: optStr,
    description: optStr,
    dimensions: optStr,
    weight: optFloat,
    color: optStr,
    material: optStr,
    origin: optStr,
    warranty: optStr,
    brand: optStr,
    status: optStr.default('Đang bán'),
    supplyType: optStr.default('Vật tư lưu kho'),
    leadTimeDays: optInt,
    location: optStr,
    image: optStr,
    coreBoard: optStr,
    surfaceCode: optStr,
    categoryId: z.string().optional().nullable().default(null),
}).strict();

// Update schema — NO .default() values, so only explicitly sent fields update
export const productUpdateSchema = z.object({
    name: z.string().trim().min(1).optional(),
    code: z.string().trim().optional(),
    category: z.string().trim().optional(),
    unit: z.string().trim().optional(),
    importPrice: updFloat,
    salePrice: updFloat,
    stock: updInt,
    minStock: updInt,
    supplier: updStr,
    description: updStr,
    dimensions: updStr,
    weight: updFloat,
    color: updStr,
    material: updStr,
    origin: updStr,
    warranty: updStr,
    brand: updStr,
    status: updStr,
    supplyType: updStr,
    leadTimeDays: updInt,
    location: updStr,
    image: updStr,
    coreBoard: updStr,
    surfaceCode: updStr,
    categoryId: z.string().optional().nullable(),
}).strict();
